version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_1706Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_1706.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GIT_1706Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2066
- serviceName: project.siqa_git_1706.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_1706Project
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2066
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2066
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2066
